version: '3.8'

# https://github.com/nacos-group/nacos-docker/blob/master/example/standalone-derby.yaml

services:
  mysql:
    image: mysql:${MYSQL_VERSION}
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      TZ: Asia/Shanghai
    env_file:
      # 账号密码都在这个文件里面设置
      - ./env/mysql.env
    command:
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --explicit_defaults_for_timestamp=true
      --lower_case_table_names=1
    volumes:
      - ./mysql/data:/var/lib/mysql
      # https://hub.docker.com/_/mysql  Initializing a fresh instance
      - ./mysql/mysql-schema.sql:/docker-entrypoint-initdb.d/nacos-mysql.sql
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      interval: 5s
      timeout: 10s
      retries: 10
    networks:
      nacos_net:
        ipv4_address: 172.16.238.12

  redis:
    image: redis:${REDIS_VERSION}
    container_name: redis
    environment:
      TZ: Asia/Shanghai
    command: redis-server --requirepass ${REDIS_PASSWORD}
    networks:
      nacos_net:
        ipv4_address: 172.16.238.14
    ports:
      - "6379:6379"
    volumes:
      - ./redis/data/:/var/lib/redis

  nacos:
    image: nacos/nacos-server:${NACOS_VERSION}
    container_name: nacos
    environment:
      TZ: Asia/Shanghai
      NACOS_AUTH_ENABLE: true
    networks:
      nacos_net:
        ipv4_address: 172.16.238.13
    env_file:
      - ./env/nacos-standlone-mysql.env
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - ./nacos/standalone-logs/:/home/nacos/logs
    ports:
      - "8848:8848"
      - "9848:9848"


networks:
  nacos_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/24