version: '3.8'

# https://github.com/nacos-group/nacos-docker/blob/master/example/standalone-derby.yaml

services: 
  nacos:
    image: nacos/nacos-server:${NACOS_VERSION}
    container_name: nacos
    networks:
      nacos_net:
        ipv4_address: 172.16.238.11
    env_file: 
      - ./env/nacos-standlone-mysql.env
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - ./nacos/standalone-logs/:/home/nacos/logs
    ports:
      - "8848:8848"
      - "9848:9848"
  
  mysql:
    image: mysql
    container_name: mysql
    build:
      context: .
      dockerfile: ./image/mysql/8/Dockerfile
    networks:
      nacos_net:
        ipv4_address: 172.16.238.12
    ports:
      - 3306:3306
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWROD}
    command:
      --default-authentication-plugin=mysql_native_password
      --explicit_defaults_for_timestamp=true
      --lower_case_table_names=1
    volumes:
      - ./mysql/data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      interval: 5s
      timeout: 10s
      retries: 10

  redis:
    image: redis:${REDIS_VERSION}
    container_name: redis
    command: redis-server --requirepass ${REDIS_PASSWROD}
    networks:
      nacos_net:
        ipv4_address: 172.16.238.13
    ports:
      - "6379:6379"
    volumes:
      - ./redis/data/:/var/lib/redis

networks:
  nacos_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/24