version: "3.8"
services:
  rabbitmq:
    image: rabbitmq:3.13.6-management
    container_name: rabbitmq
    restart: always
    volumes:
      - ./data/:/var/lib/rabbitmq/
      - ./logs/:/var/log/rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
#  https://www.rabbitmq.com/docs/configure#supported-environment-variables
#  https://www.rabbitmq.com/docs/configure
      - TZ=Asia/Shanghai
      - RABBITMQ_DEFAULT_USER=root # 默认管理员账号
      - RABBITMQ_DEFAULT_PASS=123456 # 默认管理密码


