version: '3'
services:
  redis:
    image: redis:6.2-rc2-alpine3.12
    container_name: redis
    command: redis-server --requirepass 123456
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/var/lib/redis